version: '3'
services:
    laravel:
        image: mob_composer:latest
        container_name: hello_comp
        ports:
            - 8080:8000
        volumes:
            - ./php:/src
        command: sh /src/entrypoint.sh

        